name: Semgrep

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/semgrep.yml
  schedule:
    - cron: '20 17 * * *' # Adjust schedule as needed

jobs:
  build_and_scan:
    name: Generate packages.lock.json and run Semgrep
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'  # Use the version relevant to your project

      - name: Restore packages and generate packages.lock.json
        run: |
          cd src/Web/Web.csproj
          dotnet restore -p:RestorePackagesWithLockFile=True

      - name: Run Semgrep scan
        uses: semgrep/semgrep-action@v1
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
