name: NuGet and Semgrep Workflow

on:
  push:
    branches:
      - main

jobs:
  nuget-task:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Move to Project Directory
      working-directory: eShopModernizedMVCSolution/src/eShopModernizedMVC
      run: pwd

    - name: Download NuGet CLI
      run: curl -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

    - name: Migrate packages.config to PackageReference
      working-directory: eShopModernizedMVCSolution/src/eShopModernizedMVC
      run: |
        $packages = [xml](Get-Content packages.config)
        $references = @()

        foreach ($package in $packages.packages.package) {
            $id = $package.id
            $version = $package.version
            if ($id -and $version) {
                $references += "<PackageReference Include='$id' Version='$version' />"
            }
        }

        $csprojPath = ".\eShopModernizedMVC.csproj"
        $csproj = Get-Content $csprojPath
        $csproj = $csproj -replace '<None Include="packages.config" />', ''
        $csproj = $csproj -replace '</Project>', "<ItemGroup>$($references -join '`n')</ItemGroup></Project>"
        $csproj | Set-Content $csprojPath

    - name: Enable RestorePackagesWithLockFile
      working-directory: eShopModernizedMVCSolution/src/eShopModernizedMVC
      run: |
        $fileContent = Get-Content .\eShopModernizedMVC.csproj
        $newContent = $fileContent -replace "</PropertyGroup>", "<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile></PropertyGroup>"
        $newContent | Set-Content .\eShopModernizedMVC.csproj

    - name: Restore Dependencies and Generate Lock File
      working-directory: eShopModernizedMVCSolution/src/eShopModernizedMVC
      run: dotnet restore

    - name: Upload Updated Project
      uses: actions/upload-artifact@v3
      with:
        name: updated-project
        path: eShopModernizedMVCSolution/src/eShopModernizedMVC

  semgrep-task:
    runs-on: ubuntu-latest
    needs: nuget-task
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Download Updated Project
      uses: actions/download-artifact@v3
      with:
        name: updated-project

    - name: Move to Project Directory
      working-directory: eShopModernizedMVCSolution/src/eShopModernizedMVC
      run: pwd

    - name: Install Semgrep
      run: pip install semgrep

    - name: Run Semgrep Analysis
      working-directory: eShopModernizedMVCSolution/src/eShopModernizedMVC
      run: semgrep --config=p/ci .
